### ISSUE TITLE
Takiyuaqattak, NWT

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#391]
**Name:**
Rainbird, R.H., Bédard, J.H., and Williamson, N., 2013. Geology, Takiyuaqattak, Victoria Island, Northwest Territories; Geological Survey of Canada, Canadian Geoscience Map 104 (preliminary), scale 1:50 000. doi:10.4095/293344

**Source URL:**
https://doi.org/10.4095/293344

**Estimated scale:**

**Folder name:**
nwt_taki

**Dataset names:**
nwt_taki
nwt_taki_lines
nwt_taki_points

**Number of bedrock polygons:**
157

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,name,age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_taki where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descrip,new_type,ST_MakeValid(geom) FROM sources.nwt_taki_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nwt_taki_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 244
https://dev.macrostrat.org/burwell#10/71.125/-115.5

Had to update a few data in polygons. Age was given as "Cenozoic" for something that was clearly Quaternary (always use most specific age). Quaternary units didn't have a lithology description. This one was ok to leave as-is on submission because it is a bit of a judgment call. But, in general, it is important for lithology to be specified either in description or in a lith field. 

update sources.nwt_taki set age='Quaternary',early_id=421,late_id=421 where age='Cenozoic';
update sources.nwt_taki set descrip='sand, gravel, mud: alluvium, glacial drift' where descrip='Quaternary sediments.';
